import "server-only";

import {
  createCipheriv,
  createDecipheriv,
  createHmac,
  hkdfSync,
  randomBytes,
  randomInt,
} from "node:crypto";

/**
 * Family invite codes.
 *
 * A code has two jobs that pull in opposite directions:
 *
 *   1. Someone types it in to join, so we must find the household from the
 *      code alone — that needs a DETERMINISTIC transform we can put a unique
 *      index on.
 *   2. An owner has to be able to read the code back to share it again, so we
 *      cannot simply hash it the way a password is hashed.
 *
 * So each household stores both:
 *
 *   codeIndex      HMAC-SHA256(code) — deterministic, unique, indexed. This is
 *                  a "blind index": it is what join looks up, and it leaks
 *                  nothing without the server key.
 *   codeCiphertext AES-256-GCM(code) — randomised IV, authenticated. This is
 *                  what an owner decrypts to display the code again.
 *
 * The plaintext code is never written to a column. A database dump on its own
 * yields neither the code nor a way to test a guess against it — both halves
 * are keyed by FAMILY_CODE_SECRET, which lives only in the environment.
 */

/**
 * Crockford Base32. Excludes I, L, O and U by design: the first three are
 * indistinguishable from 1 and 0 when read off a screen and typed by someone
 * else, and dropping U keeps a random code from spelling something unfortunate.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const CODE_LENGTH = 10; // 32^10 ≈ 2^50 — far past guessing at family scale
const GROUP_SIZE = 5; // displayed as XXXXX-XXXXX

const IV_BYTES = 12; // 96 bits, the size GCM is defined for
const TAG_BYTES = 16;
const KEY_BYTES = 32;

/**
 * Versioned so the ciphertext format can change later without ambiguity about
 * how an existing row was written.
 */
const SCHEME = "v1";

const SECRET_ENV = "FAMILY_CODE_SECRET";
const MIN_SECRET_BYTES = 32;

interface CodeKeys {
  readonly index: Buffer;
  readonly encryption: Buffer;
}

let cachedKeys: CodeKeys | null = null;

/**
 * One env secret, two independent sub-keys via HKDF. Using the same key for
 * both the blind index and the cipher would let one primitive's output say
 * something about the other's; separating them costs nothing.
 */
function keys(): CodeKeys {
  if (cachedKeys) return cachedKeys;

  const raw = process.env[SECRET_ENV];
  if (!raw) {
    throw new Error(
      `${SECRET_ENV} is not set. Generate one with: openssl rand -base64 32`,
    );
  }

  const secret = Buffer.from(raw, "base64");
  if (secret.length < MIN_SECRET_BYTES) {
    throw new Error(
      `${SECRET_ENV} must decode to at least ${MIN_SECRET_BYTES} bytes of base64. ` +
        `Generate one with: openssl rand -base64 32`,
    );
  }

  const derive = (info: string) =>
    Buffer.from(hkdfSync("sha256", secret, Buffer.alloc(0), info, KEY_BYTES));

  cachedKeys = {
    index: derive("family-code-index-v1"),
    encryption: derive("family-code-encryption-v1"),
  };
  return cachedKeys;
}

/**
 * Fails fast at startup rather than at the first join attempt. Call this from
 * anywhere that would rather find out now than mid-form.
 */
export function assertFamilyCodeSecret(): void {
  keys();
}

/** A fresh code, in canonical (unformatted, uppercase) form. */
export function generateFamilyCode(): string {
  let code = "";
  // randomInt is CSPRNG-backed and rejection-samples internally, so this is
  // uniform over the alphabet — Math.random() would not be.
  for (let index = 0; index < CODE_LENGTH; index += 1) {
    code += ALPHABET[randomInt(ALPHABET.length)];
  }
  return code;
}

/**
 * Canonicalises whatever the user actually typed: any casing, with or without
 * the dash, with stray spaces. Applies Crockford's confusion rules (O reads as
 * 0, I and L read as 1) so a code copied off a screen by eye still resolves.
 *
 * Returns null rather than throwing — a bad code is normal user input, not an
 * exceptional condition.
 */
export function normalizeFamilyCode(raw: string): string | null {
  const cleaned = raw
    .toUpperCase()
    .replace(/[\s-]/g, "")
    .replace(/O/g, "0")
    .replace(/[IL]/g, "1");

  if (cleaned.length !== CODE_LENGTH) return null;
  for (const character of cleaned) {
    if (!ALPHABET.includes(character)) return null;
  }
  return cleaned;
}

/** `XXXXX-XXXXX`. Display only — never store or look up the formatted form. */
export function formatFamilyCode(code: string): string {
  const groups: string[] = [];
  for (let index = 0; index < code.length; index += GROUP_SIZE) {
    groups.push(code.slice(index, index + GROUP_SIZE));
  }
  return groups.join("-");
}

/**
 * The deterministic lookup value. Normalises first so a code typed with a dash
 * and a code generated by us map to the same index.
 */
export function familyCodeIndex(code: string): string {
  const normalized = normalizeFamilyCode(code);
  if (!normalized) throw new Error("Cannot index a malformed family code.");
  return createHmac("sha256", keys().index).update(normalized).digest("hex");
}

/** AES-256-GCM. Layout: scheme "." base64(iv ‖ tag ‖ ciphertext). */
export function encryptFamilyCode(code: string): string {
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv("aes-256-gcm", keys().encryption, iv);
  const ciphertext = Buffer.concat([cipher.update(code, "utf8"), cipher.final()]);
  const payload = Buffer.concat([iv, cipher.getAuthTag(), ciphertext]);
  return `${SCHEME}.${payload.toString("base64")}`;
}

/**
 * Reverses encryptFamilyCode. Throws if the row was written under a different
 * scheme, or if the authentication tag does not verify — a tampered or
 * truncated ciphertext must never decrypt to a usable code.
 */
export function decryptFamilyCode(stored: string): string {
  const separator = stored.indexOf(".");
  if (separator === -1) throw new Error("Stored family code is malformed.");

  const scheme = stored.slice(0, separator);
  if (scheme !== SCHEME) {
    throw new Error(`Unsupported family code scheme "${scheme}".`);
  }

  const payload = Buffer.from(stored.slice(separator + 1), "base64");
  if (payload.length <= IV_BYTES + TAG_BYTES) {
    throw new Error("Stored family code is truncated.");
  }

  const decipher = createDecipheriv(
    "aes-256-gcm",
    keys().encryption,
    payload.subarray(0, IV_BYTES),
  );
  decipher.setAuthTag(payload.subarray(IV_BYTES, IV_BYTES + TAG_BYTES));

  return Buffer.concat([
    decipher.update(payload.subarray(IV_BYTES + TAG_BYTES)),
    decipher.final(),
  ]).toString("utf8");
}

/** Everything a household row needs to store one freshly minted code. */
export interface FamilyCodeRecord {
  readonly code: string; // plaintext, for showing the creator once
  readonly codeIndex: string;
  readonly codeCiphertext: string;
}

export function mintFamilyCode(): FamilyCodeRecord {
  const code = generateFamilyCode();
  return {
    code,
    codeIndex: familyCodeIndex(code),
    codeCiphertext: encryptFamilyCode(code),
  };
}
