import {
  AlarmClock,
  Apple,
  Baby,
  Backpack,
  Bath,
  Bed,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Brush,
  BrushCleaning,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  Cat,
  CookingPot,
  Dog,
  Droplets,
  Dumbbell,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  GraduationCap,
  Guitar,
  Hammer,
  Heart,
  Laptop,
  Leaf,
  ListChecks,
  Mail,
  Moon,
  Music,
  Palette,
  PawPrint,
  Pencil,
  Phone,
  Piano,
  Pill,
  Plane,
  Recycle,
  Sandwich,
  Shirt,
  ShoppingCart,
  Soup,
  Sparkles,
  Sprout,
  SquareCheckBig,
  Star,
  Sun,
  Toilet,
  Trash2,
  Trophy,
  Tv,
  Utensils,
  WashingMachine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons a task may carry, keyed by a stable string that is what Task.icon
 * stores. Rendered by lookup, so an unknown key — including the emoji the
 * column held before this list existed — falls back to the default rather
 * than reaching the renderer. Same pattern as household icons.
 *
 * Grouped loosely by what a family actually assigns: chores, care, school,
 * food, getting about, and a few for fun. Order is the picker's order.
 */
export const TASK_ICONS: Readonly<Record<string, LucideIcon>> = {
  check: SquareCheckBig,
  list: ListChecks,
  bed: Bed,
  bath: Bath,
  toilet: Toilet,
  brush: Brush,
  clean: BrushCleaning,
  laundry: WashingMachine,
  shirt: Shirt,
  trash: Trash2,
  recycle: Recycle,
  dishes: Utensils,
  cooking: CookingPot,
  soup: Soup,
  sandwich: Sandwich,
  apple: Apple,
  groceries: ShoppingCart,
  plant: Sprout,
  water: Droplets,
  flower: Flower2,
  leaf: Leaf,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  paw: PawPrint,
  baby: Baby,
  pill: Pill,
  alarm: AlarmClock,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  book: BookOpen,
  pencil: Pencil,
  backpack: Backpack,
  graduation: GraduationCap,
  calculator: Calculator,
  laptop: Laptop,
  phone: Phone,
  mail: Mail,
  briefcase: Briefcase,
  wrench: Wrench,
  hammer: Hammer,
  car: Car,
  bus: Bus,
  bike: Bike,
  plane: Plane,
  walk: Footprints,
  dumbbell: Dumbbell,
  trophy: Trophy,
  music: Music,
  guitar: Guitar,
  piano: Piano,
  palette: Palette,
  camera: Camera,
  tv: Tv,
  game: Gamepad2,
  cake: Cake,
  flame: Flame,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
};

export const DEFAULT_TASK_ICON = "check";

export const TASK_ICON_KEYS: readonly string[] = Object.keys(TASK_ICONS);

export function isTaskIconKey(value: unknown): value is string {
  return typeof value === "string" && Object.hasOwn(TASK_ICONS, value);
}

/** The component for a key; the default for anything unknown or unset. */
export function taskIcon(key: string | null | undefined): LucideIcon {
  return key && isTaskIconKey(key) ? TASK_ICONS[key] : TASK_ICONS[DEFAULT_TASK_ICON];
}
